(cl:defpackage aruco_hand_eye-srv
  (:use )
  (:export
   "ARUCO_INFO"
   "<ARUCO_INFO-REQUEST>"
   "ARUCO_INFO-REQUEST"
   "<ARUCO_INFO-RESPONSE>"
   "ARUCO_INFO-RESPONSE"
   "GET_CURR_POS"
   "<GET_CURR_POS-REQUEST>"
   "GET_CURR_POS-REQUEST"
   "<GET_CURR_POS-RESPONSE>"
   "GET_CURR_POS-RESPONSE"
   "HAND_EYE_CALIBRATION"
   "<HAND_EYE_CALIBRATION-REQUEST>"
   "HAND_EYE_CALIBRATION-REQUEST"
   "<HAND_EYE_CALIBRATION-RESPONSE>"
   "HAND_EYE_CALIBRATION-RESPONSE"
  ))

