// Generated by gencpp from file aruco_hand_eye/aruco_infoRequest.msg
// DO NOT EDIT!


#ifndef ARUCO_HAND_EYE_MESSAGE_ARUCO_INFOREQUEST_H
#define ARUCO_HAND_EYE_MESSAGE_ARUCO_INFOREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace aruco_hand_eye
{
template <class ContainerAllocator>
struct aruco_infoRequest_
{
  typedef aruco_infoRequest_<ContainerAllocator> Type;

  aruco_infoRequest_()
    : cmd()
    , id(0)  {
    }
  aruco_infoRequest_(const ContainerAllocator& _alloc)
    : cmd(_alloc)
    , id(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _cmd_type;
  _cmd_type cmd;

   typedef int64_t _id_type;
  _id_type id;





  typedef boost::shared_ptr< ::aruco_hand_eye::aruco_infoRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::aruco_hand_eye::aruco_infoRequest_<ContainerAllocator> const> ConstPtr;

}; // struct aruco_infoRequest_

typedef ::aruco_hand_eye::aruco_infoRequest_<std::allocator<void> > aruco_infoRequest;

typedef boost::shared_ptr< ::aruco_hand_eye::aruco_infoRequest > aruco_infoRequestPtr;
typedef boost::shared_ptr< ::aruco_hand_eye::aruco_infoRequest const> aruco_infoRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::aruco_hand_eye::aruco_infoRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::aruco_hand_eye::aruco_infoRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::aruco_hand_eye::aruco_infoRequest_<ContainerAllocator1> & lhs, const ::aruco_hand_eye::aruco_infoRequest_<ContainerAllocator2> & rhs)
{
  return lhs.cmd == rhs.cmd &&
    lhs.id == rhs.id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::aruco_hand_eye::aruco_infoRequest_<ContainerAllocator1> & lhs, const ::aruco_hand_eye::aruco_infoRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace aruco_hand_eye

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::aruco_hand_eye::aruco_infoRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::aruco_hand_eye::aruco_infoRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aruco_hand_eye::aruco_infoRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aruco_hand_eye::aruco_infoRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aruco_hand_eye::aruco_infoRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aruco_hand_eye::aruco_infoRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::aruco_hand_eye::aruco_infoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5e4ce8b3f259efb471169b58c08d8e1e";
  }

  static const char* value(const ::aruco_hand_eye::aruco_infoRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5e4ce8b3f259efb4ULL;
  static const uint64_t static_value2 = 0x71169b58c08d8e1eULL;
};

template<class ContainerAllocator>
struct DataType< ::aruco_hand_eye::aruco_infoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aruco_hand_eye/aruco_infoRequest";
  }

  static const char* value(const ::aruco_hand_eye::aruco_infoRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::aruco_hand_eye::aruco_infoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string    cmd\n"
"int64   id\n"
"\n"
;
  }

  static const char* value(const ::aruco_hand_eye::aruco_infoRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::aruco_hand_eye::aruco_infoRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cmd);
      stream.next(m.id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct aruco_infoRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::aruco_hand_eye::aruco_infoRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::aruco_hand_eye::aruco_infoRequest_<ContainerAllocator>& v)
  {
    s << indent << "cmd: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.cmd);
    s << indent << "id: ";
    Printer<int64_t>::stream(s, indent + "  ", v.id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARUCO_HAND_EYE_MESSAGE_ARUCO_INFOREQUEST_H
