// Generated by gencpp from file yolo_detection/ROI.msg
// DO NOT EDIT!


#ifndef YOLO_DETECTION_MESSAGE_ROI_H
#define YOLO_DETECTION_MESSAGE_ROI_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace yolo_detection
{
template <class ContainerAllocator>
struct ROI_
{
  typedef ROI_<ContainerAllocator> Type;

  ROI_()
    : object_name()
    , x(0)
    , y(0)  {
    }
  ROI_(const ContainerAllocator& _alloc)
    : object_name(_alloc)
    , x(0)
    , y(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _object_name_type;
  _object_name_type object_name;

   typedef int32_t _x_type;
  _x_type x;

   typedef int32_t _y_type;
  _y_type y;





  typedef boost::shared_ptr< ::yolo_detection::ROI_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yolo_detection::ROI_<ContainerAllocator> const> ConstPtr;

}; // struct ROI_

typedef ::yolo_detection::ROI_<std::allocator<void> > ROI;

typedef boost::shared_ptr< ::yolo_detection::ROI > ROIPtr;
typedef boost::shared_ptr< ::yolo_detection::ROI const> ROIConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yolo_detection::ROI_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yolo_detection::ROI_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::yolo_detection::ROI_<ContainerAllocator1> & lhs, const ::yolo_detection::ROI_<ContainerAllocator2> & rhs)
{
  return lhs.object_name == rhs.object_name &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::yolo_detection::ROI_<ContainerAllocator1> & lhs, const ::yolo_detection::ROI_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace yolo_detection

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::yolo_detection::ROI_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yolo_detection::ROI_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yolo_detection::ROI_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yolo_detection::ROI_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yolo_detection::ROI_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yolo_detection::ROI_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yolo_detection::ROI_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aac12b3583057ebcad7306916635123f";
  }

  static const char* value(const ::yolo_detection::ROI_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaac12b3583057ebcULL;
  static const uint64_t static_value2 = 0xad7306916635123fULL;
};

template<class ContainerAllocator>
struct DataType< ::yolo_detection::ROI_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yolo_detection/ROI";
  }

  static const char* value(const ::yolo_detection::ROI_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yolo_detection::ROI_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string object_name\n"
"int32 x\n"
"int32 y\n"
;
  }

  static const char* value(const ::yolo_detection::ROI_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yolo_detection::ROI_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.object_name);
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ROI_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yolo_detection::ROI_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yolo_detection::ROI_<ContainerAllocator>& v)
  {
    s << indent << "object_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.object_name);
    s << indent << "x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int32_t>::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YOLO_DETECTION_MESSAGE_ROI_H
