// Generated by gencpp from file yolo_detection/ROI_array.msg
// DO NOT EDIT!


#ifndef YOLO_DETECTION_MESSAGE_ROI_ARRAY_H
#define YOLO_DETECTION_MESSAGE_ROI_ARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <yolo_detection/ROI.h>

namespace yolo_detection
{
template <class ContainerAllocator>
struct ROI_array_
{
  typedef ROI_array_<ContainerAllocator> Type;

  ROI_array_()
    : ROI_list()  {
    }
  ROI_array_(const ContainerAllocator& _alloc)
    : ROI_list(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::yolo_detection::ROI_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::yolo_detection::ROI_<ContainerAllocator> >::other >  _ROI_list_type;
  _ROI_list_type ROI_list;





  typedef boost::shared_ptr< ::yolo_detection::ROI_array_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yolo_detection::ROI_array_<ContainerAllocator> const> ConstPtr;

}; // struct ROI_array_

typedef ::yolo_detection::ROI_array_<std::allocator<void> > ROI_array;

typedef boost::shared_ptr< ::yolo_detection::ROI_array > ROI_arrayPtr;
typedef boost::shared_ptr< ::yolo_detection::ROI_array const> ROI_arrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yolo_detection::ROI_array_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yolo_detection::ROI_array_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::yolo_detection::ROI_array_<ContainerAllocator1> & lhs, const ::yolo_detection::ROI_array_<ContainerAllocator2> & rhs)
{
  return lhs.ROI_list == rhs.ROI_list;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::yolo_detection::ROI_array_<ContainerAllocator1> & lhs, const ::yolo_detection::ROI_array_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace yolo_detection

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::yolo_detection::ROI_array_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yolo_detection::ROI_array_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yolo_detection::ROI_array_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yolo_detection::ROI_array_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yolo_detection::ROI_array_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yolo_detection::ROI_array_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yolo_detection::ROI_array_<ContainerAllocator> >
{
  static const char* value()
  {
    return "98a75627170c780818a3f3f2d48f82c4";
  }

  static const char* value(const ::yolo_detection::ROI_array_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x98a75627170c7808ULL;
  static const uint64_t static_value2 = 0x18a3f3f2d48f82c4ULL;
};

template<class ContainerAllocator>
struct DataType< ::yolo_detection::ROI_array_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yolo_detection/ROI_array";
  }

  static const char* value(const ::yolo_detection::ROI_array_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yolo_detection::ROI_array_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ROI[] ROI_list\n"
"\n"
"================================================================================\n"
"MSG: yolo_detection/ROI\n"
"string object_name\n"
"int32 x\n"
"int32 y\n"
;
  }

  static const char* value(const ::yolo_detection::ROI_array_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yolo_detection::ROI_array_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ROI_list);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ROI_array_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yolo_detection::ROI_array_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yolo_detection::ROI_array_<ContainerAllocator>& v)
  {
    s << indent << "ROI_list[]" << std::endl;
    for (size_t i = 0; i < v.ROI_list.size(); ++i)
    {
      s << indent << "  ROI_list[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::yolo_detection::ROI_<ContainerAllocator> >::stream(s, indent + "    ", v.ROI_list[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // YOLO_DETECTION_MESSAGE_ROI_ARRAY_H
